---
id: 20150922_rabbit
base_name: my-profile
tags:
- rabbit
- profile
- sapporo
presentation_date: 2015-09-22
version: 2015.09.22.3
licenses:
- CC BY 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: omuko
  email: irasally@gmail.com
  rubygems_user: irasally
  slideshare_user: irasally
  speaker_deck_user: 
